//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hwj.UserControls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hwj.UserControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 清空记录 的本地化字符串。
        /// </summary>
        internal static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接设置 的本地化字符串。
        /// </summary>
        internal static string ConnectionSetting {
            get {
                return ResourceManager.GetString("ConnectionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写多个Email地址,请用 &quot;{0}&quot; 分隔 的本地化字符串。
        /// </summary>
        internal static string EamilTips {
            get {
                return ResourceManager.GetString("EamilTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回车 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        internal static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的日期 的本地化字符串。
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此地址似乎拼写有误 的本地化字符串。
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下地址似乎拼写有误:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string InvalidEmails {
            get {
                return ResourceManager.GetString("InvalidEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}个以上的字符 的本地化字符串。
        /// </summary>
        internal static string InvalidInputString {
            get {
                return ResourceManager.GetString("InvalidInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]为无效的数字格式 的本地化字符串。
        /// </summary>
        internal static string InvalidNumberic {
            get {
                return ResourceManager.GetString("InvalidNumberic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码中不能含有 &quot;{0}&quot; 字符 的本地化字符串。
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前找不到你所需要的记录 的本地化字符串。
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件异常!
        ///-{0} 的本地化字符串。
        /// </summary>
        internal static string OpenFileException {
            get {
                return ResourceManager.GetString("OpenFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap page_search {
            get {
                object obj = ResourceManager.GetObject("page_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 共{0}条记录 的本地化字符串。
        /// </summary>
        internal static string PageRecordCount {
            get {
                return ResourceManager.GetString("PageRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交数据前,请将资料填写完整 的本地化字符串。
        /// </summary>
        internal static string RequiredInfo {
            get {
                return ResourceManager.GetString("RequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}条记录 的本地化字符串。
        /// </summary>
        internal static string ReturnRecord {
            get {
                return ResourceManager.GetString("ReturnRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空格 的本地化字符串。
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接测试成功! 的本地化字符串。
        /// </summary>
        internal static string TestConnectionSucceeded {
            get {
                return ResourceManager.GetString("TestConnectionSucceeded", resourceCulture);
            }
        }
    }
}
